export const PROPERTY_CREATE_REQUEST = 'PROPERTY_CREATE_REQUEST'
export const PROPERTY_CREATE_SUCCESS = 'PROPERTY_CREATE_SUCCESS'
export const PROPERTY_CREATE_FAIL = 'PROPERTY_CREATE_FAIL'

export const PROPERTY_DELETE_REQUEST = 'PROPERTY_DELETE_REQUEST'
export const PROPERTY_DELETE_SUCCESS = 'PROPERTY_DELETE_SUCCESS'
export const PROPERTY_DELETE_FAIL = 'PROPERTY_DELETE_FAIL'

export const PROPERTY_DETAILS_REQUEST = 'PROPERTY_DETAILS_REQUEST'
export const PROPERTY_DETAILS_SUCCESS = 'PROPERTY_DETAILS_SUCCESS'
export const PROPERTY_DETAILS_FAIL = 'PROPERTY_DETAILS_FAIL'

export const ALL_PROPERTIES_REQUEST = 'ALL_PROPERTIES_REQUEST'
export const ALL_PROPERTIES_SUCCESS = 'ALL_PROPERTIES_SUCCESS'
export const ALL_PROPERTIES_FAIL = 'ALL_PROPERTIES_FAIL'

export const SEARCH_PROPERTIES_REQUEST = 'SEARCH_PROPERTIES_REQUEST'
export const SEARCH_PROPERTIES_SUCCESS = 'SEARCH_PROPERTIES_SUCCESS'
export const SEARCH_PROPERTIES_FAIL = 'SEARCH_PROPERTIES_FAIL'
