// LOGIN
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

// LOGOUT
export const USER_LOGOUT = "USER_LOGOUT";

// SIGN_UP
export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL";

// USER_UPDATES
export const PROFILE_PIC_UPDATE_REQUEST = 'PROFILE_PIC_UPDATE_REQUEST';
export const PROFILE_PIC_UPDATE_SUCCESS = 'PROFILE_PIC_UPDATE_SUCCESS';
export const PROFILE_PIC_UPDATE_FAIL = 'PROFILE_PIC_UPDATE_FAIL';

// SIGNED_TOKEN_REQUEST
export const GET_USER_DATA_REQUEST = 'GET_USER_DATA_REQUEST'
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS'
export const GET_USER_DATA_FAIL = 'GET_USER_DATA_FAIL'